# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Apache SystemDS
title: Apache SystemDS - Declarative Large-Scale Machine Learning
email: dev@systemds.apache.org
description: Apache SystemDS provides an optimal workplace for Machine Learning using big data
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://systemds.apache.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# if 'analytics_on' is true, analytics section will be rendered on the HTML pages
analytics_on: true
analytics_provider: google_universal
analytics_google_universal_tracking_id : UA-71553733-1

source: _src

exclude:
  - _sass
  - _scripts

# https://jekyllrb.com/docs/collections/
collections:
  datasets:
    output: true



